In [32]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [33]:
df_train=pd.read_csv('train.zip')
df_test = pd.read_csv('test.zip')

In [34]:
df_train.head()

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
0,0,36,694,4,4,4,3,1,4,1,...,4,3,1,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
1,1,56,651,5,5,5,5,5,4,4,...,5,4,3,0,0.0,Male,Loyal Customer,Business travel,Business,True
2,2,31,1371,3,4,2,5,3,3,3,...,4,5,3,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
3,3,10,1616,3,5,3,3,3,3,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
4,4,23,481,3,4,3,4,5,3,5,...,5,3,5,5,0.0,Female,disloyal Customer,Business travel,Eco,False

In [35]:
df_test.head()

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Leg room service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class
0,699635,25,1197,4,4,4,2,3,4,3,...,5,2,1,3,0,0.0,Female,disloyal Customer,Business travel,Eco
1,699636,36,829,5,5,5,5,5,4,5,...,2,4,3,5,0,0.0,Male,Loyal Customer,Business travel,Eco
2,699637,45,472,4,5,5,5,4,4,4,...,3,1,3,4,0,0.0,Male,Loyal Customer,Business travel,Eco
3,699638,45,762,2,2,2,5,3,2,3,...,4,4,4,3,0,0.0,Female,disloyal Customer,Business travel,Business
4,699639,34,594,1,2,1,1,2,1,2,...,4,2,1,2,0,0.0,Male,Loyal Customer,Personal Travel,Eco Plus

In [36]:
save=df_test.copy()

In [37]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699635 entries, 0 to 699634
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 699635 non-null  int64
 1   Age                                699635 non-null  int64
 2   Flight Distance                    699635 non-null  int64
 3   Inflight wifi service              699635 non-null  int64
 4   Departure/Arrival time convenient  699635 non-null  int64
 5   Ease of Online booking             699635 non-null  int64
 6   Gate location                      699635 non-null  int64
 7   Food and drink                     699635 non-null  int64
 8   Online boarding                    699635 non-null  int64
 9   Seat comfort                       699635 non-null  int64
 10  Inflight entertainment             699635 non-null  int64
 11  On-board service                   699635 non-null  int64
 12  Leg room service                   699635 non-null  int64
 13  Baggage handling                   699635 non-null  int64
 14  Checkin service                    699635 non-null  int64
 15  Cleanliness                        699635 non-null  int64
 16  Departure Delay in Minutes         699635 non-null  int64
 17  Arrival Delay in Minutes           699343 non-null  float64
 18  Gender                             699635 non-null  object
 19  Customer Type                      699635 non-null  object
 20  Type of Travel                     699635 non-null  object
 21  Class                              699635 non-null  object
 22  satisfaction                       699635 non-null  bool
dtypes: bool(1), float64(1), int64(17), object(4)
memory usage: 118.1+ MB

In [38]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299844 entries, 0 to 299843
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 299844 non-null  int64
 1   Age                                299844 non-null  int64
 2   Flight Distance                    299844 non-null  int64
 3   Inflight wifi service              299844 non-null  int64
 4   Departure/Arrival time convenient  299844 non-null  int64
 5   Ease of Online booking             299844 non-null  int64
 6   Gate location                      299844 non-null  int64
 7   Food and drink                     299844 non-null  int64
 8   Online boarding                    299844 non-null  int64
 9   Seat comfort                       299844 non-null  int64
 10  Inflight entertainment             299844 non-null  int64
 11  On-board service                   299844 non-null  int64
 12  Leg room service                   299844 non-null  int64
 13  Baggage handling                   299844 non-null  int64
 14  Checkin service                    299844 non-null  int64
 15  Cleanliness                        299844 non-null  int64
 16  Departure Delay in Minutes         299844 non-null  int64
 17  Arrival Delay in Minutes           299714 non-null  float64
 18  Gender                             299844 non-null  object
 19  Customer Type                      299844 non-null  object
 20  Type of Travel                     299844 non-null  object
 21  Class                              299844 non-null  object
dtypes: float64(1), int64(17), object(4)
memory usage: 50.3+ MB

In [39]:
print(df_train.columns)
print(df_test.columns)

Index(['id', 'Age', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Gender',
       'Customer Type', 'Type of Travel', 'Class', 'satisfaction'],
      dtype='object')
Index(['id', 'Age', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Gender',
       'Customer Type', 'Type of Travel', 'Class'],
      dtype='object')

In [40]:
df_train.corr(numeric_only=True)['satisfaction'].sort_values(ascending=False)

satisfaction                         1.000000
Online boarding                      0.559583
Inflight entertainment               0.430755
Seat comfort                         0.401488
Flight Distance                      0.370038
On-board service                     0.346618
Cleanliness                          0.338853
Leg room service                     0.330116
Inflight wifi service                0.291275
Baggage handling                     0.258118
Checkin service                      0.249799
Food and drink                       0.218058
Age                                  0.202708
Ease of Online booking               0.190878
Gate location                        0.022834
id                                   0.000125
Departure Delay in Minutes          -0.035815
Departure/Arrival time convenient   -0.049185
Arrival Delay in Minutes            -0.051641
Name: satisfaction, dtype: float64

In [41]:
from sklearn.preprocessing import LabelEncoder

cols = ['Gender', 'Customer Type', 'Type of Travel', 'Class']

for col in cols:
    le = LabelEncoder()
    df_train[col] = le.fit_transform(df_train[col])
    df_test[col] = le.transform(df_test[col])

le = LabelEncoder()
df_train['satisfaction'] = le.fit_transform(df_train['satisfaction'])

In [42]:
X_train['Arrival Delay in Minutes'] = X_train['Arrival Delay in Minutes'].fillna(
    X_train['Arrival Delay in Minutes'].median()
)

X_test['Arrival Delay in Minutes'] = X_test['Arrival Delay in Minutes'].fillna(
    X_train['Arrival Delay in Minutes'].median()
)

In [43]:
X_train = df_train.drop('satisfaction', axis=1)
y_train = df_train['satisfaction']

X_test = df_test.copy()